#!/bin/bash


echo ""
echo "Creating: rttmo.pro"
shopt -s extglob 
echo $CFLAGS
qmake-qt4 -project \
		-o rttmo.pro \
		CONFIG+=debug \
		QT+=xml \
		QMAKE_CFLAGS+="-fopenmp" \
		QMAKE_CXXFLAGS+="-fopenmp" \
		QMAKE_LFLAGS+="-fopenmp" \
		LIBS+="-L /usr/local/lib -lltdl -lpthread -lm"  \
		LIBS+="-ldc1394" \
		LIBS+="-lcv -lcvaux -lhighgui	" \
		INCLUDEPATH+="/usr/include/opencv" \
		INCLUDEPATH+="/usr/local/include/opencv" \

echo "Creating: Makefile"
qmake-qt4 -makefile

echo "Type 'make' to compile everything"
echo ""
